name: flutter_lab_6
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  # cloud_firestore: ^4.12.2
  # firebase_auth: ^4.12.1
  # firebase_core: ^2.21.0
  # google_sign_in: ^6.1.6
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.1.0
  freezed_annotation: ^2.4.1
  riverpod: ^2.4.6
  flutter_riverpod: ^2.4.6
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  freezed: ^2.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
