name: flutter_lab_6
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  cloud_firestore: ^4.12.2
  firebase_auth: ^4.12.1
  firebase_core: ^2.21.0
  google_sign_in: ^6.1.6
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.1.0
  freezed_annotation:
  riverpod: ^0.12.2
  flutter_riverpod: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^1.11.0
  freezed: ^0.12.7

flutter:
  uses-material-design: true
