// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions 
{
  static FirebaseOptions get currentPlatform 
  {
    if (kIsWeb) 
    {
      return web;
    }
    switch (defaultTargetPlatform) 
    {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError
        (
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError
        (
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError
        (
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions
  (
    apiKey: 'AIzaSyD1t_Qk_h0371rHWe3VClAdYXV3L3KFLrs',
    appId: '1:844034924495:web:a4c1ba0c2a3e6a7de0fcba',
    messagingSenderId: '844034924495',
    projectId: 'flutter-lab-6',
    authDomain: 'flutter-lab-6.firebaseapp.com',
    storageBucket: 'flutter-lab-6.appspot.com',
    measurementId: 'G-G8PFN9RRFP',
  );

  static const FirebaseOptions android = FirebaseOptions
  (
    apiKey: 'AIzaSyAjFncHMSfSRjrhGPVy6uy0Joc1k4ImsIw',
    appId: '1:844034924495:android:93d36a6bcdf126f0e0fcba',
    messagingSenderId: '844034924495',
    projectId: 'flutter-lab-6',
    storageBucket: 'flutter-lab-6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions
  (
    apiKey: 'AIzaSyC9C1qtFdjn-aCasHrTACaEjYjrdJAn4PA',
    appId: '1:844034924495:ios:8c4951cbbc3d20fce0fcba',
    messagingSenderId: '844034924495',
    projectId: 'flutter-lab-6',
    storageBucket: 'flutter-lab-6.appspot.com',
    iosBundleId: 'com.example.flutterLab6',
  );

  static const FirebaseOptions macos = FirebaseOptions
  (
    apiKey: 'AIzaSyC9C1qtFdjn-aCasHrTACaEjYjrdJAn4PA',
    appId: '1:844034924495:ios:cc4943ffb9b09cbce0fcba',
    messagingSenderId: '844034924495',
    projectId: 'flutter-lab-6',
    storageBucket: 'flutter-lab-6.appspot.com',
    iosBundleId: 'com.example.flutterLab6.RunnerTests',
  );
}
